### ISSUE TITLE
dlib HOG face detector - zero division error

### ISSUE THREAD

**Issue by exnx** [natanielruiz/deep-head-pose#28]
Hi, has anyone tried using the HOG based dlib face detector with the deep head pose model?

The dlib CNN model was even slower for me. Since I'm using just a CPU, the test was like 30 secs a frame... so maybe using a HOG model would be slightly faster.

However, when I make the appropriate swap between the dlib cnn and HOG detectors, I get a zero division error when I pass the image the transform object.  Note - I made sure to get the proper bounding box format output from the HOG detector, so I don't think that's the problem.

**This is the error:**
Traceback (most recent call last):
  File "code/test_on_video_dlib.py", line 153, in <module>
    img = transformations(img)
  File "/anaconda3/envs/deepheadpose-env/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 49, in __call__
  File "/anaconda3/envs/deepheadpose-env/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 175, in __call__
  File "/anaconda3/envs/deepheadpose-env/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/functional.py", line 203, in resize
ZeroDivisionError: division by zero

**Comment by exnx** [comment]
I found the bug - had to do with my input shape.
