### ISSUE TITLE
torch version on gpu

### ISSUE THREAD

**Issue by sunny0315** [natanielruiz/deep-head-pose#69]
the version of torch must >=1.1.0 when run on gpu?
with torch=0.4.0(cuda=0.8.61) ,I made an error 'Aborted(core dump)' but on cpu is well

**Comment by mogualgo** [comment]
I have the same question.

**Comment by shahroudy** [comment]
I tried both 0.4.1 and 1.1 (of PyTorch) and it works on both with very minor changes in the code.

**Comment by flyduck** [comment]
> I tried both 0.4.1 and 1.1 (of PyTorch) and it works on both with very minor changes in the code.

@shahroudy  hi, could you help tell where to change? when use 1.1 pytorch?thanks!

**Comment by shahroudy** [comment]
> > I tried both 0.4.1 and 1.1 (of PyTorch) and it works on both with very minor changes in the code.
> 
> @shahroudy hi, could you help tell where to change? when use 1.1 pytorch?thanks!

You can find it in my forked repository.

**Comment by kaisark** [comment]
@shahroudy I was able to use your fork with Pytorch 1.3, but I did run into the following error that was fixed with casting...

Environment:
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.87.00

Error:
(dl4cvpy36-pytorch1.3) ubuntu@ip-172-31-0-76:~/cviz/deep-head-pose$ python code/test_on_video_dlib.py --snapshot models/hopenet_snapshot_a1.pkl --face_model mmod_human_face_detector.dat --video 2019-11-26-173255.webm.mp4 --n_frames 100 --fps 15
Loading snapshot.
Loading data.
/home/ubuntu/.virtualenvs/dl4cvpy36-pytorch1.3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:211: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Ready to test network.
1
Traceback (most recent call last):
  File "code/test_on_video_dlib.py", line 171, in <module>
    img = cv2_frame[y_min:y_max,x_min:x_max]
TypeError: slice indices must be integers or None or have an __index__ method

Fix:
img = cv2_frame[int(y_min):int(y_max),int(x_min):int(x_max)]

![Computervision GIF-downsized_largegaze2](https://user-images.githubusercontent.com/3580312/69693038-0d2caf00-10a2-11ea-8ac4-b5794dbec53a.gif)

![Computervision GIF-downsized_largegaze1](https://user-images.githubusercontent.com/3580312/69693041-11f16300-10a2-11ea-8ad2-769b50ddfbb0.gif)

**Comment by LamLuong** [comment]
> @shahroudy I was able to use your fork with Pytorch 1.3, but I did run into the following error that was fixed with casting...
> 
> Environment:
> PyTorch version: 1.3.0
> Is debug build: No
> CUDA used to build PyTorch: 10.1.243
> 
> OS: Ubuntu 16.04.6 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> CMake version: version 3.5.1
> 
> Python version: 3.6
> Is CUDA available: Yes
> CUDA runtime version: 10.1.243
> GPU models and configuration: GPU 0: Tesla K80
> Nvidia driver version: 418.87.00
> 
> Error:
> (dl4cvpy36-pytorch1.3) ubuntu@ip-172-31-0-76:~/cviz/deep-head-pose$ python code/test_on_video_dlib.py --snapshot models/hopenet_snapshot_a1.pkl --face_model mmod_human_face_detector.dat --video 2019-11-26-173255.webm.mp4 --n_frames 100 --fps 15
> Loading snapshot.
> Loading data.
> /home/ubuntu/.virtualenvs/dl4cvpy36-pytorch1.3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:211: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
> "please use transforms.Resize instead.")
> Ready to test network.
> 1
> Traceback (most recent call last):
> File "code/test_on_video_dlib.py", line 171, in
> img = cv2_frame[y_min:y_max,x_min:x_max]
> TypeError: slice indices must be integers or None or have an **index** method
> 
> Fix:
> img = cv2_frame[int(y_min):int(y_max),int(x_min):int(x_max)]
> 
> ![Computervision GIF-downsized_largegaze2](https://user-images.githubusercontent.com/3580312/69693038-0d2caf00-10a2-11ea-8ac4-b5794dbec53a.gif)
> 
> ![Computervision GIF-downsized_largegaze1](https://user-images.githubusercontent.com/3580312/69693041-11f16300-10a2-11ea-8ad2-769b50ddfbb0.gif)

Your result is so great! How many epochs did you train? I trained with 100 epochs but then I had got the same result of (yaw, pitch , roll) on different inputs images
